# Generated by Django 2.2.7 on 2020-02-20 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('BaseModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sppermissions',
            table='sp_permissions',
        ),
    ]
