# Generated by Django 2.2.7 on 2020-02-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BaseModule', '0002_auto_20200220_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sppermissions',
            name='permissions',
            field=models.IntegerField(default=0),
        ),
    ]
