# Generated by Django 2.2.7 on 2020-03-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('size', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent', models.DateTimeField()),
                ('state', models.BooleanField(default=True)),
                ('attachments', models.ManyToManyField(to='KgbModule.Attachment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KgbModule.Member')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KgbModule.Message')),
                ('type', models.SmallIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KgbModule.Message')),
            ],
            bases=('KgbModule.message',),
        ),
    ]
