# Generated by Django 2.2.7 on 2020-03-27 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KgbModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='message',
            name='guild_id',
            field=models.IntegerField(default=0),
        ),
    ]
